import ipaddress
from chalicelib.utils import network_to_keys

networks = [
    network_to_keys(ipaddress.ip_network(network[0]), **network[1])
    for network in
    [
        ['10.248.0.0/17', {'class': 'prd'}],
        ['10.248.0.0/20',
            {'group': 'PR-Core',
             'desc': 'Velocity ENC Core and Shared Services',
             'class': 'prd'}],
        ['10.248.16.0/20',
            {'desc': 'cm0', 'account': 'wpl-wrk-cm0-prd', 'class': 'prd'}],
        ['10.248.32.0/20', {'group': 'PR-B', 'desc': 'TBA', 'class': 'prd'}],
        ['10.248.32.0/21',
         {'desc': 'CDS Production', 'account': 'wpl-wrk-cds-prd', 'class': 'prd'}],
        ['10.248.40.0/23',
         {'desc': 'Engineering', 'account': 'wpl-wrk-eng-prd', 'class': 'prd'}],
        ['10.248.42.0/23',
         {'desc': 'Workspace (Access Service Line)',
          'account': 'wpl-wrk-wkspace-prd',
          'class': 'prd'}],
        ['10.248.44.0/24',
         {'desc': 'SAP', 'account': 'wpl-wrk-sap-prd', 'class': 'prd'}],
        ['10.248.45.0/24',
         {'desc': 'SAP', 'account': 'wpl-wrk-sap-prd', 'class': 'prd'}],
        ['10.248.46.0/24',
         {'desc': 'SAP', 'account': 'wpl-wrk-sap-prd', 'class': 'prd'}],
        ['10.248.47.0/24',
         {'desc': 'SAP', 'account': 'wpl-wrk-sap-prd', 'class': 'prd'}],
        ['10.248.48.0/20', {'group': 'PR-C', 'desc': 'TBA', 'class': 'prd'}],
        ['10.248.48.0/23',
         {'desc': 'Engineering Data Management',
          'account': 'wpl-wrk-edm-prd',
          'class': 'prd'}],
        ['10.248.50.0/24',
         {'desc': 'Finance Multi-tenant',
          'account': 'wpl-wrk-fin-prd',
          'class': 'prd'}],
        ['10.248.51.0/24', {'desc': '', 'account': '', 'class': 'prd'}],
        ['10.248.52.0/24',
         {'desc': 'Marketing, Trading & Shipping',
          'account': 'wpl-wrk-mts-prd',
          'class': 'prd'}],
        ['10.248.53.0/24',
         {'desc': 'Marketing, Trading & Shipping',
          'account': 'wpl-wrk-mts-prd',
          'class': 'prd'}],
        ['10.248.54.0/24',
         {'desc': 'Marketing, Trading & Shipping',
          'account': 'wpl-wrk-mts-prd',
          'class': 'prd'}],
        ['10.248.55.0/24',
         {'desc': 'Marketing, Trading & Shipping',
          'account': 'wpl-wrk-mts-prd',
          'class': 'prd'}],
        ['10.248.56.0/24',
         {'desc': 'Operations Maintenance Prd',
          'account': 'wpl-wrk-opsmnt-prd',
          'class': 'prd'}],
        ['10.248.57.0/24',
         {'desc': 'Operations Maintenance Prd',
          'account': 'wpl-wrk-opsmnt-prd',
          'class': 'prd'}],
        ['10.248.58.0/24',
         {'desc': 'Operations Maintenance Prd',
          'account': 'wpl-wrk-opsmnt-prd',
          'class': 'prd'}],
        ['10.248.59.0/24',
         {'desc': 'Operations Maintenance Prd',
          'account': 'wpl-wrk-opsmnt-prd',
          'class': 'prd'}],
        ['10.248.60.0/24',
         {'desc': 'RADA ECS PRD', 'account': 'wpl-wrk-radaecs-prd', 'class': 'prd'}],
        ['10.248.61.0/24',
         {'desc': 'RADA ECS PRD', 'account': 'wpl-wrk-radaecs-prd', 'class': 'prd'}],
        ['10.248.62.0/24',
         {'desc': 'RADA ECS PRD', 'account': 'wpl-wrk-radaecs-prd', 'class': 'prd'}],
        ['10.248.63.0/24',
         {'desc': 'RADA ECS PRD', 'account': 'wpl-wrk-radaecs-prd', 'class': 'prd'}],
        ['10.248.64.0/20', {'group': 'PR-D', 'desc': 'TBA', 'class': 'prd'}],
        ['10.248.64.0/22',
         {'desc': 'Information Management', 'account': 'wrk-im-prd', 'class': 'prd'}],
        ['10.248.68.0/24',
         {'desc': 'SDIM Production', 'account': 'wpl-wrk-sdim-prd', 'class': 'prd'}],
        ['10.248.72.0/23',
         {'desc': 'Integration Team Production',
          'account': 'wpl-wrk-int-prd',
          'class': 'prd'}],
        ['10.248.74.0/23',
         {'desc': 'Security Operations Team (Network Connected)',
          'account': 'wk-secopsnc-prd',
          'class': 'prd'}],
        ['10.248.76.0/22',
         {'desc': 'Contracting and Procurement Multi-tennant',
          'account': 'wrk-candp-prd',
          'class': 'prd'}],
        ['10.248.80.0/20', {'group': 'PR-E', 'desc': 'TBA', 'class': 'prd'}],
        ['10.248.80.0/24',
         {'desc': 'Inspection Maintenance Connect',
          'account': 'wpl-wrk-imc-prd',
          'class': 'prd'}],
        ['10.248.81.0/24',
         {'desc': 'Robotics Process Automation',
          'account': 'wpl-wrk-rpa-prd',
          'class': 'prd'}],
        ['10.248.82.0/23',
         {'desc': 'Production Operations',
          'account': 'wpl-wrk-prodops-prd',
          'class': 'prd'}],
        ['10.248.84.0/24',
         {'desc': 'devtools', 'account': 'wpl-wrk-devtools-prd', 'class': 'prd'}],
        ['10.248.85.0/24',
         {'desc': 'devtools', 'account': 'wpl-wrk-devtools-prd', 'class': 'prd'}],
        ['10.248.86.0/24',
         {'desc': 'devtools', 'account': 'wpl-wrk-devtools-prd', 'class': 'prd'}],
        ['10.248.87.0/24',
         {'desc': 'devtools', 'account': 'wpl-wrk-devtools-prd', 'class': 'prd'}],
        ['10.248.88.0/24',
         {'desc': 'IAM', 'account': 'wpl-wrk-iam-prd', 'class': 'prd'}],
        ['10.248.89.0/24',
         {'desc': 'IAM', 'account': 'wpl-wrk-iam-prd', 'class': 'prd'}],
        ['10.248.90.0/24',
         {'desc': 'corpaff', 'account': 'wpl-wrk-corpaff-prd', 'class': 'prd'}],
        ['10.248.91.0/24',
         {'desc': 'corpaff', 'account': 'wpl-wrk-corpaff-prd', 'class': 'prd'}],
        ['10.248.92.0/24',
         {'desc': 'logistic (formerly CNF-only account)',
          'account': 'wpl-wrk-logistic-prd',
          'class': 'prd'}],
        ['10.248.93.0/24',
         {'desc': 'logistic', 'account': 'wpl-wrk-logistic-prd', 'class': 'prd'}],
        ['10.248.94.0/24',
         {'desc': 'security', 'account': 'wpl-ctl-security', 'class': 'prd'}],
        ['10.248.95.0/24', {'desc': '', 'account': '', 'class': 'prd'}],
        ['10.248.96.0/20', {'group': 'PR-F', 'desc': 'TBA', 'class': 'prd'}],
        ['10.248.96.0/21', {'desc': 'DPS',
                            'account': 'wrk-dps-prd', 'class': 'prd'}],
        ['10.248.104.0/21', {'desc': 'AI',
                             'account': 'wrk-ai-prd', 'class': 'prd'}],
        ['10.248.112.0/20',
         {'group': 'PR-G', 'desc': 'Early or Adhoc workloads', 'class': 'prd'}],
        ['10.248.112.0/23',
         {'desc': 'Risk and Compliance Multitenant',
          'account': 'wpl-wrk-rskcomp-prd',
          'class': 'prd'}],
        ['10.248.114.0/24',
         {'desc': 'Production Accounting System',
          'account': 'wpl-wrk-pas-prd',
          'class': 'prd'}],
        ['10.248.115.0/24',
         {'desc': 'AV Prod', 'account': 'wrk-av-prd', 'class': 'prd'}],
        ['10.248.116.0/23',
         {'desc': 'Migration Factory', 'account': 'wrk-mig-prd', 'class': 'prd'}],
        ['10.248.118.0/23',
         {'desc': 'Autonomous Intelligent Systems',
          'account': 'wrk-ais-prd',
          'class': 'prd'}],
        ['10.248.120.0/22',
         {'desc': 'IT Management Systems', 'account': 'wrk-itm-prd', 'class': 'prd'}],
        ['10.248.124.0/23',
         {'desc': 'Willow', 'account': 'wrk-wil-prd', 'class': 'prd'}],
        ['10.248.126.0/24',
         {'desc': 'Saviynt Production Environment',
          'account': 'NA / Semi Trusted',
          'class': 'prd'}],
        ['10.248.127.0/24',
         {'desc': 'Private, reuseable range',
          'account': 'AutomatedPrivateNetworkServerless OU accounts',
          'class': 'prd'}],
        ['10.249.0.0/17', {'class': 'prd'}],
        ['10.249.0.0/20',
         {'group': 'PR-H', 'desc': 'Data Science Production', 'class': 'prd'}],
        ['10.249.0.0/21',
         {'desc': 'Data Science Production',
          'account': 'wpl-wrk-datasci-prd',
          'class': 'prd'}],
        ['10.249.8.0/24',
         {'desc': 'CDS DDPIE application',
          'account': 'wpl-wrk-ddpie-prd',
          'class': 'prd'}],
        ['10.249.9.0/24',
         {'desc': 'CDS DDPIE application',
          'account': 'wpl-wrk-ddpie-prd',
          'class': 'prd'}],
        ['10.249.10.0/24',
         {'desc': 'CDS DDPIE application',
          'account': 'wpl-wrk-ddpie-prd',
          'class': 'prd'}],
        ['10.249.11.0/24',
         {'desc': 'CDS DDPIE application',
          'account': 'wpl-wrk-ddpie-prd',
          'class': 'prd'}],
        ['10.249.12.0/24',
         {'desc': 'Reservoir Simulation',
          'account': 'wpl-wrk-ressim-prd',
          'class': 'prd'}],
        ['10.249.13.0/24',
         {'desc': 'Reservoir Simulation',
          'account': 'wpl-wrk-ressim-prd',
          'class': 'prd'}],
        ['10.249.14.0/24',
         {'desc': 'Reservoir Simulation',
          'account': 'wpl-wrk-ressim-prd',
          'class': 'prd'}],
        ['10.249.15.0/24',
         {'desc': 'Reservoir Simulation',
          'account': 'wpl-wrk-ressim-prd',
          'class': 'prd'}],
        ['10.249.16.0/20', {'group': 'PR-I', 'class': 'prd'}],
        ['10.249.16.0/22',
         {'desc': 'Workspace Trusted Production',
          'account': 'wpl-wrk-wrkspct-prd',
          'class': 'prd'}],
        ['10.249.20.0/22', {'desc': '', 'account': '', 'class': 'prd'}],
        ['10.249.24.0/23',
         {'desc': 'EMS Production', 'account': 'wpl-wrk-ems-prd', 'class': 'prd'}],
        ['10.249.26.0/23',
         {'desc': 'Simple Start Workload',
          'account': 'wpl-wrk-cogent-prd',
          'class': 'prd'}],
        ['10.249.28.0/24',
         {'desc': 'DIGAMS Production',
          'account': 'wpl-wrk-digiams-prd',
          'class': 'prd'}],
        ['10.249.29.0/24',
         {'desc': 'DIGAMS Production',
          'account': 'wpl-wrk-digiams-prd',
          'class': 'prd'}],
        ['10.249.30.0/24',
         {'desc': 'DIGAMS Production',
          'account': 'wpl-wrk-digiams-prd',
          'class': 'prd'}],
        ['10.249.31.0/24',
         {'desc': 'DIGAMS Production',
          'account': 'wpl-wrk-digiams-prd',
          'class': 'prd'}],
        ['10.249.32.0/20', {'group': 'PR-J', 'class': 'prd'}],
        ['10.249.32.0/22',
         {'desc': 'Cost and Planning Production',
          'account': 'wpl-wrk-plancost-prd',
          'class': 'prd'}],
        ['10.249.36.0/23',
         {'desc': 'CDS Restricted Production',
          'account': 'wpl-wrk-cdsrest-prd',
          'class': 'prd'}],
        ['10.249.38.0/23',
         {'desc': 'CDS SSUD Production',
          'account': 'wpl-wrk-cdsssud-prd',
          'class': 'prd'}],
        ['10.249.40.0/24',
         {'desc': 'Full Wave Form Inversion',
          'account': 'wpl-wrk-geohpc-prd',
          'class': 'prd'}],
        ['10.249.41.0/24',
         {'desc': 'Full Wave Form Inversion',
          'account': 'wpl-wrk-geohpc-prd',
          'class': 'prd'}],
        ['10.249.42.0/24',
         {'desc': 'Data Driven Solutions for Data science',
          'account': 'wpl-wrk-ddssvcs-prd',
          'class': 'prd'}],
        ['10.249.43.0/24',
         {'desc': 'End-user Compute Mobile Device Management',
          'account': 'wpl-wrk-eucmdmgt-prd',
          'class': 'prd'}],
        ['10.249.44.0/22',
         {'desc': 'Data Science Solutions',
          'account': 'wpl-wrk-dds-prd',
          'class': 'prd'}],
        ['10.249.48.0/20', {'group': 'PR-K', 'class': 'prd'}],
        ['10.249.48.0/22',
         {'desc': 'SSPL Prod', 'account': 'wpl-wrk-sspl-prd', 'class': 'prd'}],
        ['10.249.52.0/22',
         {'desc': 'Process Engineering',
          'account': 'wpl-wrk-proceng-prd',
          'class': 'prd'}],
        ['10.249.56.0/21',
         {'desc': 'Netbackup Account',
          'account': 'wpl-wrk-netbackup-prd',
          'class': 'prd'}],
        ['10.249.64.0/20',
         {'desc': 'Amazon Workspaces',
          'account': 'wpl-wrk-awswrksp-prd',
          'class': 'prd'}],
        ['10.249.80.0/20', {'group': 'PR-M', 'class': 'prd'}],
        ['10.249.80.0/24',
         {'desc': 'First Priority',
          'account': 'wpl-wrk-firstprio-prd',
          'class': 'prd'}],
        ['10.249.84.0/22',
         {'desc': 'Software Reliability Engineering',
          'account': 'wpl-wrk-sre-prd',
          'class': 'prd'}],
        ['10.249.88.0/23',
         {'desc': 'OSDU', 'account': 'wpl-wrk-osdu-prd', 'class': 'prd'}],
        ['10.249.90.0/24', {'desc': '', 'account': '', 'class': 'prd'}],
        ['10.249.91.0/24',
         {'desc': '3D Printing Project',
          'account': 'wpl-wrk-3dprint-prd',
          'class': 'prd'}],
        ['10.249.92.0/24', {'desc': '', 'account': '', 'class': 'prd'}],
        ['10.249.93.0/24', {'desc': '', 'account': '', 'class': 'prd'}],
        ['10.249.94.0/24', {'desc': '', 'account': '', 'class': 'prd'}],
        ['10.249.95.0/24', {'desc': '', 'account': '', 'class': 'prd'}],
        ['10.249.96.0/20', {'group': 'PR-N', 'class': 'prd'}],
        ['10.249.96.0/23',
         {'desc': 'SharePoint 2013 Servers',
          'account': 'wpl-wrk-sharept-prd',
          'class': 'prd'}],
        ['10.249.98.0/23',
         {'desc': 'Connected AV Solution',
          'account': 'wpl-wrk-connav-prd',
          'class': 'prd'}],
        ['10.249.100.0/22',
         {'desc': 'Data Science Tools',
          'account': 'wpl-wrk-dstools-prd',
          'class': 'prd'}],
        ['10.249.104.0/24',
         {'desc': 'Data Science Apps',
          'account': 'wpl-wrk-dsapps-prd',
          'class': 'prd'}],
        ['10.249.105.0/24', {'desc': '', 'account': '', 'class': 'prd'}],
        ['10.249.106.0/23',
         {'desc': 'Jira migration', 'account': 'wpl-wrk-jira-prd', 'class': 'prd'}],
        ['10.249.108.0/24',
         {'desc': 'Power BI', 'account': 'wpl-wrk-pbi-prd', 'class': 'prd'}],
        ['10.249.109.0/24',
         {'desc': 'Tableau Server', 'account': 'wpl-wrk-tabl-prd', 'class': 'prd'}],
        ['10.249.110.0/23',
         {'desc': 'Maintenance Hub',
          'account': 'wpl-wrk-mainthub-prd',
          'class': 'prd'}],
        ['10.249.112.0/20', {'group': 'PR-O', 'class': 'prd'}],
        ['10.249.112.0/24',
         {'desc': 'Cyber', 'account': 'wpl-wrk-cybsiem-prd', 'class': 'prd'}],
        ['10.249.113.0/24',
         {'desc': 'Cyber', 'account': 'wpl-wrk-cybsiem-prd', 'class': 'prd'}],
        ['10.249.114.0/24',
         {'desc': 'Cyber', 'account': 'wpl-wrk-cybsiem-prd', 'class': 'prd'}],
        ['10.249.115.0/24',
         {'desc': 'Cyber', 'account': 'wpl-wrk-cybsiem-prd', 'class': 'prd'}],
        ['10.249.116.0/24',
         {'desc': 'Cyber Syslog',
          'account': 'wpl-wrk-cybsyslog-prd',
          'class': 'prd'}],
        ['10.249.117.0/24',
         {'desc': 'Cyber Syslog',
          'account': 'wpl-wrk-cybsyslog-prd',
          'class': 'prd'}],
        ['10.249.118.0/24',
         {'desc': 'Cyber Syslog',
          'account': 'wpl-wrk-cybsyslog-prd',
          'class': 'prd'}],
        ['10.249.119.0/24',
         {'desc': 'Cyber Syslog',
          'account': 'wpl-wrk-cybsyslog-prd',
          'class': 'prd'}],
        ['10.249.120.0/24',
         {'desc': 'Telecoms', 'account': 'wpl-wrk-telecoms-prd', 'class': 'prd'}],
        ['10.249.121.0/24',
         {'desc': 'All Main', 'account': 'wpl-wrk-aimain-prd', 'class': 'prd'}],
        ['10.249.122.0/24',
         {'desc': 'GTO', 'account': 'wpl-wrk-gto-prd', 'class': 'prd'}],
        ['10.249.123.0/24',
         {'desc': 'GTO', 'account': 'wpl-wrk-gto-prd', 'class': 'prd'}],
        ['10.249.124.0/24',
         {'desc': 'All Knowledge',
          'account': 'wpl-wrk-aiknowlg-prd',
          'class': 'prd'}],
        ['10.249.125.0/24',
         {'desc': 'Gravitas Weight Management',
          'account': 'wpl-wrk-weightmgt-prd',
          'class': 'prd'}],
        ['10.249.126.0/24', {'desc': '', 'account': '', 'class': 'prd'}],
        ['10.249.127.0/24',
         {'desc': 'RBM', 'account': 'wpl-wrk-rbm-prd', 'class': 'prd'}],
        ['10.248.128.0/17', {'class': 'np'}],
        ['10.248.128.0/20',
         {'desc': 'shared_services', 'account': 'wpl-ops-np', 'class': 'np'}],
        ['10.248.144.0/20', {'group': 'NP-A', 'desc': 'TBA', 'class': 'np'}],
        ['10.248.144.0/23',
         {'desc': 'Willow', 'account': 'wpl-wrk-wil-np', 'class': 'np'}],
        ['10.248.146.0/23',
         {'desc': 'CDS Proof Of Concept',
          'account': 'wpl-wrk-cdspoc-np',
          'class': 'np'}],
        ['10.248.152.0/23',
         {'desc': 'Data Science Proof of Concept',
          'account': 'wpl-wrk-dscpoc-np',
          'class': 'np'}],
        ['10.248.154.0/23',
         {'desc': 'Integration Team Development',
          'account': 'wpl-wrk-int-np',
          'class': 'np'}],
        ['10.248.156.0/22',
         {'desc': 'Information Management', 'account': 'wrk-im-np', 'class': 'np'}],
        ['10.248.160.0/20', {'group': 'NP-B', 'desc': 'TBA', 'class': 'np'}],
        ['10.248.160.0/23',
         {'desc': 'Engineering Data Management',
          'account': 'wpl-wrk-edm-np',
          'class': 'np'}],
        ['10.248.162.0/23',
         {'desc': 'Engineering', 'account': 'wpl-wrk-eng-np', 'class': 'np'}],
        ['10.248.164.0/23',
         {'desc': 'Workspace (Access Service Line)',
          'account': 'wpl-wrk-wkspace-np',
          'class': 'np'}],
        ['10.248.166.0/24',
         {'desc': 'Inspection Maintenance Connect',
          'account': 'wpl-wrk-imc-np',
          'class': 'np'}],
        ['10.248.167.0/24',
         {'desc': 'Robotics Process Automation',
          'account': 'wpl-wrk-rpa-np',
          'class': 'np'}],
        ['10.248.168.0/23',
         {'desc': 'Production Operations',
          'account': 'wpl-wrk-prodops-np',
          'class': 'np'}],
        ['10.248.170.0/24',
         {'desc': 'Marketing, Trading & Shipping',
          'account': 'wpl-wrk-mts-np',
          'class': 'np'}],
        ['10.248.171.0/24',
         {'desc': 'Marketing, Trading & Shipping',
          'account': 'wpl-wrk-mts-np',
          'class': 'np'}],
        ['10.248.172.0/24',
         {'desc': 'IAM', 'account': 'wpl-wrk-iam-np', 'class': 'np'}],
        ['10.248.173.0/24',
         {'desc': 'IAM', 'account': 'wpl-wrk-iam-np', 'class': 'np'}],
        ['10.248.174.0/23',
         {'desc': 'Security Operations Team (Network Connected)',
          'account': 'wpl-wrk-secopsnc-np',
          'class': 'np'}],
        ['10.248.176.0/20', {'group': 'NP-C', 'desc': 'TBA', 'class': 'np'}],
        ['10.248.176.0/24',
         {'desc': 'devtools', 'account': 'wpl-wrk-devtools-np', 'class': 'np'}],
        ['10.248.177.0/24',
         {'desc': 'devtools', 'account': 'wpl-wrk-devtools-np', 'class': 'np'}],
        ['10.248.178.0/24',
         {'desc': 'devtools', 'account': 'wpl-wrk-devtools-np', 'class': 'np'}],
        ['10.248.179.0/24',
         {'desc': 'devtools', 'account': 'wpl-wrk-devtools-np', 'class': 'np'}],
        ['10.248.180.0/24',
         {'desc': 'corpaff', 'account': 'wpl-wrk-corpaff-np', 'class': 'np'}],
        ['10.248.181.0/24',
         {'desc': 'corpaff', 'account': 'wpl-wrk-corpaff-np', 'class': 'np'}],
        ['10.248.182.0/24',
         {'desc': 'logistic (formerly CNF-only account)',
          'account': 'wpl-wrk-logistic-np',
          'class': 'np'}],
        ['10.248.183.0/24',
         {'desc': 'logistic', 'account': 'wpl-wrk-logistic-np', 'class': 'np'}],
        ['10.248.184.0/24',
         {'desc': 'Subsea and Pipelines',
          'account': 'wpl-wrk-sspl-np',
          'class': 'np'}],
        ['10.248.185.0/24',
         {'desc': 'Subsea and Pipelines',
          'account': 'wpl-wrk-sspl-np',
          'class': 'np'}],
        ['10.248.186.0/24',
         {'desc': 'Subsea and Pipelines',
          'account': 'wpl-wrk-sspl-np',
          'class': 'np'}],
        ['10.248.187.0/24',
         {'desc': 'Subsea and Pipelines',
          'account': 'wpl-wrk-sspl-np',
          'class': 'np'}],
        ['10.248.188.0/24',
         {'desc': 'SAP', 'account': 'wpl-wrk-sap-np', 'class': 'np'}],
        ['10.248.189.0/24',
         {'desc': 'SAP', 'account': 'wpl-wrk-sap-np', 'class': 'np'}],
        ['10.248.190.0/24',
         {'desc': 'SAP', 'account': 'wpl-wrk-sap-np', 'class': 'np'}],
        ['10.248.191.0/24',
         {'desc': 'SAP', 'account': 'wpl-wrk-sap-np', 'class': 'np'}],
        ['10.248.192.0/20', {'group': 'NP-D', 'desc': 'TBA', 'class': 'np'}],
        ['10.248.200.0/21',
         {'desc': 'CDS Non Production', 'account': 'wpl-wrk-cds-np', 'class': 'np'}],
        ['10.248.192.0/24',
         {'desc': 'Finance Multi-tenant',
          'account': 'wpl-wrk-fin-np',
          'class': 'np'}],
        ['10.248.193.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.248.194.0/23',
         {'desc': 'Risk and Compliance Non Production',
          'account': 'wpl-wrk-rskcomp-np',
          'class': 'np'}],
        ['10.248.196.0/24',
         {'desc': 'Operations Maintenance NP',
          'account': 'wpl-wrk-opsmnt-np',
          'class': 'np'}],
        ['10.248.197.0/24',
         {'desc': 'Operations Maintenance NP',
          'account': 'wpl-wrk-opsmnt-np',
          'class': 'np'}],
        ['10.248.198.0/24',
         {'desc': 'Operations Maintenance NP',
          'account': 'wpl-wrk-opsmnt-np',
          'class': 'np'}],
        ['10.248.199.0/24',
         {'desc': 'Operations Maintenance NP',
          'account': 'wpl-wrk-opsmnt-np',
          'class': 'np'}],
        ['10.248.208.0/20', {'group': 'NP-E', 'desc': 'TBA', 'class': 'np'}],
        ['10.248.208.0/24',
         {'desc': 'RADA ECS NP', 'account': 'wpl-wrk-radaecs-np', 'class': 'np'}],
        ['10.248.209.0/24',
         {'desc': 'RADA ECS NP', 'account': 'wpl-wrk-radaecs-np', 'class': 'np'}],
        ['10.248.210.0/24',
         {'desc': 'RADA ECS NP', 'account': 'wpl-wrk-radaecs-np', 'class': 'np'}],
        ['10.248.211.0/24',
         {'desc': 'RADA ECS NP', 'account': 'wpl-wrk-radaecs-np', 'class': 'np'}],
        ['10.248.212.0/24',
         {'desc': 'SDIM NP', 'account': 'wpl-wrk-sdim-np', 'class': 'np'}],
        ['10.248.213.0/24',
         {'desc': 'SDIM NP', 'account': 'wpl-wrk-sdim-np', 'class': 'np'}],
        ['10.248.214.0/24',
         {'desc': 'SDIM NP', 'account': 'wpl-wrk-sdim-np', 'class': 'np'}],
        ['10.248.215.0/24',
         {'desc': 'SDIM NP', 'account': 'wpl-wrk-sdim-np', 'class': 'np'}],
        ['10.248.216.0/22',
         {'desc': 'Cops Playpen', 'account': 'wrk-copspp-np', 'class': 'np'}],
        ['10.248.220.0/24',
         {'desc': 'SAP (SAPHANA)', 'account': 'wrk-saphana-np', 'class': 'np'}],
        ['10.248.221.0/24',
         {'desc': 'SAP (SAPHANA)', 'account': 'wrk-saphana-np', 'class': 'np'}],
        ['10.248.222.0/24',
         {'desc': 'SAP (SAPHANA)', 'account': 'wrk-saphana-np', 'class': 'np'}],
        ['10.248.223.0/24',
         {'desc': 'SAP (SAPHANA)', 'account': 'wrk-sahanap-np', 'class': 'np'}],
        ['10.248.224.0/20', {'group': 'NP-F', 'desc': 'TBA', 'class': 'np'}],
        ['10.248.224.0/24',
         {'desc': 'PP / Intelligent Autonomous Systems (IoT)',
          'account': 'wrk-pp-np',
          'class': 'np'}],
        ['10.248.225.0/24',
         {'desc': 'PP / Intelligent Autonomous Systems (IoT)',
          'account': 'wrk-pp-np',
          'class': 'np'}],
        ['10.248.226.0/23',
         {'desc': 'SharePoint 2013 Servers',
          'account': 'wpl-wrk-sharept-np',
          'class': 'np'}],
        ['10.248.228.0/22', {'desc': 'PP',
                             'account': 'wrk-pp-np', 'class': 'np'}],
        ['10.248.232.0/24', {'desc': 'AI',
                             'account': 'wrk-np-ai', 'class': 'np'}],
        ['10.248.233.0/24', {'desc': 'AI',
                             'account': 'wrk-np-ai', 'class': 'np'}],
        ['10.248.234.0/24', {'desc': 'AI',
                             'account': 'wrk-np-ai', 'class': 'np'}],
        ['10.248.235.0/24', {'desc': 'AI',
                             'account': 'wrk-np-ai', 'class': 'np'}],
        ['10.248.236.0/24', {'desc': 'AI',
                             'account': 'wrk-np-ai', 'class': 'np'}],
        ['10.248.237.0/24', {'desc': 'AI',
                             'account': 'wrk-np-ai', 'class': 'np'}],
        ['10.248.238.0/24', {'desc': 'AI',
                             'account': 'wrk-np-ai', 'class': 'np'}],
        ['10.248.239.0/24', {'desc': 'AI',
                             'account': 'wrk-np-ai', 'class': 'np'}],
        ['10.248.240.0/20',
         {'group': 'NP-G', 'desc': 'Early or Adhoc workloads', 'class': 'np'}],
        ['10.248.240.0/24',
         {'desc': 'GTO non prod', 'account': 'wpl-wrk-gto-np', 'class': 'np'}],
        ['10.248.241.0/24',
         {'desc': 'GTO non prod', 'account': 'wpl-wrk-gto-np', 'class': 'np'}],
        ['10.248.242.0/24',
         {'desc': 'AV Non-Production', 'account': 'wpl-wrk-av-np', 'class': 'np'}],
        ['10.248.243.0/24',
         {'desc': 'Sitewise POC', 'account': 'wpl-wrk-stwsepoc-np', 'class': 'np'}],
        ['10.248.244.0/24',
         {'desc': 'Intelligent Autonomous Systems (IoT)',
          'account': 'wpl-wrk-ias-np',
          'class': 'np'}],
        ['10.248.245.0/24',
         {'desc': 'Intelligent Autonomous Systems (IoT)',
          'account': 'wpl-wrk-ias-np',
          'class': 'np'}],
        ['10.248.246.0/24',
         {'desc': 'Intelligent Autonomous Systems (IoT)',
          'account': 'wpl-wrk-ias-np',
          'class': 'np'}],
        ['10.248.247.0/24',
         {'desc': 'Intelligent Autonomous Systems (IoT)',
          'account': 'wpl-wrk-ias-np',
          'class': 'np'}],
        ['10.248.248.0/22',
         {'desc': 'Contracting and Procurement Multitenant',
          'account': 'wpl-wrk-candp-np',
          'class': 'np'}],
        ['10.248.252.0/23',
         {'desc': 'Saviynt Development and Test Environments',
          'account': 'NA / Semi Trusted',
          'class': 'np'}],
        ['10.248.254.0/24',
         {'desc': 'Bake', 'account': 'wpl-ops-bake', 'class': 'np'}],
        ['10.248.255.0/24',
         {'desc': 'Private, reuseable range',
          'account': 'AutomatedPrivateNetworkServerless OU accounts',
          'class': 'np'}],
        ['10.249.128.0/17', {'class': 'np'}],
        ['10.249.128.0/20',
         {'group': 'NP-H', 'desc': 'Data Science Non Production', 'class': 'np'}],
        ['10.249.128.0/21',
         {'desc': 'Data Science Non Production',
          'account': 'wpl-wrk-datasci-np',
          'class': 'np'}],
        ['10.249.136.0/24',
         {'desc': 'CDS DDPIE application',
          'account': 'wpl-wrk-ddpie-np',
          'class': 'np'}],
        ['10.249.137.0/24',
         {'desc': 'CDS DDPIE application',
          'account': 'wpl-wrk-ddpie-np',
          'class': 'np'}],
        ['10.249.138.0/24',
         {'desc': 'CDS DDPIE application',
          'account': 'wpl-wrk-ddpie-np',
          'class': 'np'}],
        ['10.249.139.0/24',
         {'desc': 'CDS DDPIE application',
          'account': 'wpl-wrk-ddpie-np',
          'class': 'np'}],
        ['10.249.140.0/24',
         {'desc': 'ITM NP account', 'account': 'wpl-wrk-itm-np', 'class': 'np'}],
        ['10.249.141.0/24',
         {'desc': 'ITM NP account', 'account': 'wpl-wrk-itm-np', 'class': 'np'}],
        ['10.249.142.0/24',
         {'desc': 'ITM NP account', 'account': 'wpl-wrk-itm-np', 'class': 'np'}],
        ['10.249.143.0/24',
         {'desc': 'ITM NP account', 'account': 'wpl-wrk-itm-np', 'class': 'np'}],
        ['10.249.144.0/20', {'group': 'NP-I', 'class': 'np'}],
        ['10.249.144.0/22',
         {'desc': 'Workspace Trusted Dev',
          'account': 'wpl-wrk-wrkspct-np',
          'class': 'np'}],
        ['10.249.148.0/22', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.152.0/22',
         {'desc': 'Brownfields', 'account': 'wpl-wrk-brownfld-np', 'class': 'np'}],
        ['10.249.156.0/23',
         {'desc': 'EMS Non Production', 'account': 'wpl-wrk-ems-np', 'class': 'np'}],
        ['10.249.158.0/24',
         {'desc': 'Pen test Non Prod',
          'account': 'wpl-wrk-pentst-np',
          'class': 'np'}],
        ['10.249.159.0/24',
         {'desc': 'wpl-sci-scipp-np', 'account': 'wpl-sci-scipp-np', 'class': 'np'}],
        ['10.249.160.0/20', {'group': 'NP-J', 'class': 'np'}],
        ['10.249.160.0/24',
         {'desc': 'Auto Plant POC Account',
          'account': 'wpl-wrk-appoc-np',
          'class': 'np'}],
        ['10.249.161.0/24',
         {'desc': 'Transit Gateway Test',
          'account': 'wpl-wrk-tgwtest-np',
          'class': 'np'}],
        ['10.249.162.0/23',
         {'desc': 'OT Archive Account', 'account': 'wpl-wrk-ota-np', 'class': 'np'}],
        ['10.249.164.0/24',
         {'desc': 'DIGAMS Non Prod', 'account': 'wpl-wrk-digams-np', 'class': 'np'}],
        ['10.249.165.0/24',
         {'desc': 'DIGAMS Non Prod', 'account': 'wpl-wrk-digams-np', 'class': 'np'}],
        ['10.249.166.0/24',
         {'desc': 'DIGAMS Non Prod', 'account': 'wpl-wrk-digams-np', 'class': 'np'}],
        ['10.249.167.0/24',
         {'desc': 'DIGAMS Non Prod', 'account': 'wpl-wrk-digams-np', 'class': 'np'}],
        ['10.249.168.0/22',
         {'desc': 'Cost and Planning Non Prod',
          'account': 'wpl-wrk-plancost-np',
          'class': 'np'}],
        ['10.249.172.0/23',
         {'desc': 'CDS Restricted Non Production',
          'account': 'wpl-wrk-cdsrest-np',
          'class': 'np'}],
        ['10.249.174.0/23',
         {'desc': 'CDS SSUD Non prod',
          'account': 'wpl-wrk-cdsssud-np',
          'class': 'np'}],
        ['10.249.176.0/20', {'group': 'NP-K', 'class': 'np'}],
        ['10.249.176.0/24',
         {'desc': 'Full Wave Form Inversion',
          'account': 'wpl-wrk-geohpc-np',
          'class': 'np'}],
        ['10.249.177.0/24',
         {'desc': 'Full Wave Form Inversion',
          'account': 'wpl-wrk-geohpc-np',
          'class': 'np'}],
        ['10.249.178.0/23',
         {'desc': 'Simple Start Workload',
          'account': 'wpl-wrk-cogent-np',
          'class': 'np'}],
        ['10.249.180.0/22',
         {'desc': 'Data Science Solutions',
          'account': 'wpl-wrk-dds-np',
          'class': 'np'}],
        ['10.249.184.0/22',
         {'desc': 'Process Engineering',
          'account': 'wpl-wrk-proceng-np',
          'class': 'np'}],
        ['10.249.185.0/24',
         {'desc': '', 'account': 'wpl-wrk-proceng-np', 'class': 'np'}],
        ['10.249.186.0/24',
         {'desc': '', 'account': 'wpl-wrk-proceng-np', 'class': 'np'}],
        ['10.249.187.0/24',
         {'desc': '', 'account': 'wpl-wrk-proceng-np', 'class': 'np'}],
        ['10.249.188.0/23',
         {'desc': 'Cyber PlayPen account',
          'account': 'wpl-wrk-cyberpp-np',
          'class': 'np'}],
        ['10.249.190.0/24',
         {'desc': 'Telecoms', 'account': 'wpl-wrk-telecoms-np', 'class': 'np'}],
        ['10.249.191.0/24',
         {'desc': 'AI Main', 'account': 'wpl-wrk-aimain-np', 'class': 'np'}],
        ['10.249.192.0/20', {'group': 'NP-L', 'class': 'np'}],
        ['10.249.192.0/23',
         {'desc': 'Connected AV Solution',
          'account': 'wpl-wrk-connav-np',
          'class': 'np'}],
        ['10.249.194.0/24',
         {'desc': 'Data Science Apps',
          'account': 'wpl-wrk-dsapps-np',
          'class': 'np'}],
        ['10.249.195.0/24',
         {'desc': 'AI Knowledge', 'account': 'wpl-wrk-aiknowlg-np', 'class': 'np'}],
        ['10.249.196.0/22',
         {'desc': 'Data Science Tools',
          'account': 'wpl-wrk-dstools-np',
          'class': 'np'}],
        ['10.249.200.0/23',
         {'desc': 'Jira Migration', 'account': 'wpl-wrk-jira-np', 'class': 'np'}],
        ['10.249.202.0/24',
         {'desc': 'Power BI', 'account': 'wpl-wrk-pbi-np', 'class': 'np'}],
        ['10.249.203.0/24',
         {'desc': 'Tableau Server', 'account': 'wpl-wrk-tabl-np', 'class': 'np'}],
        ['10.249.204.0/23',
         {'desc': 'Maintenance Hub',
          'account': 'wpl-wrk-mainthub-np',
          'class': 'np'}],
        ['10.249.206.0/24',
         {'desc': 'SAP PRD Legacy Hosting',
          'account': 'wpl-wrk-saplegpoc-np',
          'class': 'np'}],
        ['10.249.207.0/24',
         {'desc': 'End-user Compute MobileDevice Management',
          'account': 'wpl-wrk-eucmdmgt-np',
          'class': 'np'}],
        ['10.249.208.0/20', {'group': 'NP-M', 'class': 'np'}],
        ['10.249.208.0/24',
         {'desc': 'Cyber Syslog', 'account': 'wpl-wrk-cybsyslog-np', 'class': 'np'}],
        ['10.249.209.0/24',
         {'desc': 'Cyber Syslog', 'account': 'wpl-wrk-cybsyslog-np', 'class': 'np'}],
        ['10.249.210.0/24',
         {'desc': 'Cyber Syslog', 'account': 'wpl-wrk-cybsyslog-np', 'class': 'np'}],
        ['10.249.211.0/24',
         {'desc': 'Cyber Syslog', 'account': 'wpl-wrk-cybsyslog-np', 'class': 'np'}],
        ['10.249.212.0/24',
         {'desc': 'Gravitas Weight Management',
          'account': 'wpl-wrk-weightmgt-np',
          'class': 'np'}],
        ['10.249.213.0/24',
         {'desc': 'ZScaler Private Access',
          'account': 'wpl-wrk-zpa-np',
          'class': 'np'}],
        ['10.249.214.0/24',
         {'desc': 'RBM', 'account': 'wpl-wrk-rbm-np', 'class': 'np'}],
        ['10.249.215.0/24',
         {'desc': 'First Priority',
          'account': 'wpl-wrk-firstprio-np',
          'class': 'np'}],
        ['10.249.216.0/22',
         {'desc': 'Software Reliability Engineering',
          'account': 'wpl-wrk-sre-np',
          'class': 'np'}],
        ['10.249.220.0/23',
         {'desc': 'OSDU', 'account': 'wpl-wrk-osdu-np', 'class': 'np'}],
        ['10.249.222.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.223.0/24',
         {'desc': '3D Printing Project',
          'account': 'wpl-wrk-3dprint-np',
          'class': 'np'}],
        ['10.249.224.0/20', {'group': 'NP-N', 'class': 'np'}],
        ['10.249.224.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.225.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.226.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.227.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.228.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.229.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.230.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.231.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.232.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.233.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.234.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.235.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.236.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.237.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.238.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.239.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.240.0/20', {'group': 'NP-O', 'class': 'np'}],
        ['10.249.240.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.241.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.242.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.243.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.244.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.245.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.246.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.247.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.248.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.249.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.250.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.251.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.252.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.253.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.254.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['10.249.255.0/24', {'desc': '', 'account': '', 'class': 'np'}],
        ['0.0.0.0/0', {'class': 'int'}],
        ['10.160.48.0/20',
         {'desc': 'London Point of Presence',
          'account': 'wpl-wrk-lonpop-prd',
          'class': 'int'}],
        ['10.67.128.0/20',
         {'desc': 'Oregon Point of Presence',
          'account': 'wpl-wrk-orepop-prd',
          'class': 'int'}],
        ['10.67.146.0/24',
         {'desc': 'Sitewise POC Oregon',
          'account': 'wpl-wrk-stwsepoc-np',
          'class': 'int'}]
    ]
]
